export { default as register } from './register'
export { default as login } from './login'
export { default as emailVerification } from './email-verification'
export { default as forgotMyPass } from './forgot-my-pass'
export { default as sendConfirmCode } from './send-confirm-code'